# Test a rust extension

.common: &common
  image: ubuntu:16.04
  before_script:
    - apt update
    - apt install -y curl python2.7-dev python3.5-dev build-essential tox
    - curl https://sh.rustup.rs -sSf | sh -s -- -y

test:stable:
  <<: *common
  script:
    - export PATH=$HOME/.cargo/bin:$PATH
    - rustup default stable
    - tox

test:beta:
  <<: *common
  script:
    - export PATH=$HOME/.cargo/bin:$PATH
    - rustup default beta
    - tox

test:nightly:
  <<: *common
  script:
    - export PATH=$HOME/.cargo/bin:$PATH
    - rustup default nightly
    - tox
