language: python
python:
  - "2.7"  # tox manages the python matrix
env:
  - RUST_VERSION=stable
  - RUST_VERSION=nightly
sudo: required
install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUST_VERSION
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustc -V
script:
  - sudo pip install tox
  - tox

